G10 P0 R175 S225 ; sets the standby temperature
G10 P1 R175 S225 ; sets the standby temperature
G10 P2 R175 S225 ; sets the standby temperature
G10 P3 R175 S225 ; sets the standby temperature
; generated by SuperSlicer 2.3.55 on 2021-03-30 at 19:10:03 UTC

;

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

; object:{"name":"Würfel_20mm","id":"Würfel_20mm.STL id:0 copy 0","object_center":[110.588706,99.946841,0.000000],"boundingbox_center":[110.588706,99.946841,0.100000],"boundingbox_size":[20.000000,20.000000,0.200000]}
; object:{"name":"Würfel_20mm","id":"Würfel_20mm.STL id:1 copy 0","object_center":[140.171314,100.486058,0.000000],"boundingbox_center":[140.171314,100.486058,0.100000],"boundingbox_size":[20.000000,20.000000,0.200000]}
; object:{"name":"Würfel_20mm","id":"Würfel_20mm.STL id:2 copy 0","object_center":[170.237769,99.933259,0.000000],"boundingbox_center":[170.237769,99.933259,0.100000],"boundingbox_size":[20.000000,20.000000,0.200000]}
; object:{"name":"Würfel_20mm","id":"Würfel_20mm.STL id:3 copy 0","object_center":[199.640936,100.080727,0.000000],"boundingbox_center":[199.640936,100.080727,0.100000],"boundingbox_size":[20.000000,20.000000,0.200000]}
; plater:{"center":[155.114821,100.209658,0.000000],"boundingbox_center":[155.114821,100.209658,0.100000],"boundingbox_size":[109.052230,20.552799,0.200000]}

;TYPE:Custom
; custom gcode: start_gcode
; set tool temps
G10 P0 S225 R225;
G10 P1 S225 R225;
G10 P2 S225 R225;
G10 P3 S225 R225;

; set bed temps
M140 S60 ;set bed temp fast
M190 S60 ; set bed temp + wait for it

; prepare for print
G28 Z; home all axes
G29 S1; enable MeshBedLeveling
G1 Z5 F5000 ; lift nozzle

; make sure, a tool is selected before print

T0 ; Select inital tool

; custom gcode end: start_gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; custom gcode: start_filament_gcode
; Filament gcode
; custom gcode end: start_filament_gcode
;Z:0.4
;HEIGHT:0.4
G1 Z0.400000 F21000.000
; printing object Würfel_20mm.STL id:0 copy 0
G1 E-3.50000 F2400.00000
G1 Z1.700000 F21000.000
G1 X101.417 Y90.775
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Perimeter
G1 F1800.000
G1 X119.760 Y90.775 E0.95835
G1 X119.760 Y109.119 E0.95835
G1 X101.417 Y109.119 E0.95835
G1 X101.417 Y90.835 E0.95521
G1 X101.103 Y90.461 F21000.000
G1 F1800.000
G1 X120.075 Y90.461 E0.99117
G1 X120.075 Y109.433 E0.99117
G1 X101.103 Y109.433 E0.99117
G1 X101.103 Y90.521 E0.98804
G1 X100.789 Y90.147 F21000.000
;TYPE:External perimeter
G1 F1800.000
G1 X120.389 Y90.147 E1.02400
G1 X120.389 Y109.747 E1.02400
G1 X100.789 Y109.747 E1.02400
G1 X100.789 Y90.207 E1.02087
G1 X101.135 Y90.347 F21000.000
G1 E-3.50000 F2400.00000
G1 Z0.900000 F21000.000
G1 X119.031 Y90.869
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Solid infill
G1 F1800.000
G1 X119.525 Y91.363 E0.03587
G1 X119.525 Y91.807 E0.02283
G1 X118.728 Y91.011 E0.05788
G1 X118.284 Y91.011 E0.02283
G1 X119.525 Y92.252 E0.09016
G1 X119.525 Y92.696 E0.02283
G1 X117.840 Y91.011 E0.12244
G1 X117.395 Y91.011 E0.02283
G1 X119.525 Y93.140 E0.15472
G1 X119.525 Y93.585 E0.02283
G1 X116.951 Y91.011 E0.18700
G1 X116.507 Y91.011 E0.02283
G1 X119.525 Y94.029 E0.21928
G1 X119.525 Y94.473 E0.02283
G1 X116.062 Y91.011 E0.25156
G1 X115.618 Y91.011 E0.02283
G1 X119.525 Y94.917 E0.28384
G1 X119.525 Y95.362 E0.02283
G1 X115.174 Y91.011 E0.31612
G1 X114.730 Y91.011 E0.02283
G1 X119.525 Y95.806 E0.34840
G1 X119.525 Y96.250 E0.02283
G1 X114.285 Y91.011 E0.38068
G1 X113.841 Y91.011 E0.02283
G1 X119.525 Y96.695 E0.41296
G1 X119.525 Y97.139 E0.02283
G1 X113.397 Y91.011 E0.44524
G1 X112.952 Y91.011 E0.02283
G1 X119.525 Y97.583 E0.47752
G1 X119.525 Y98.027 E0.02283
G1 X112.508 Y91.011 E0.50980
G1 X112.064 Y91.011 E0.02283
G1 X119.525 Y98.472 E0.54208
G1 X119.525 Y98.916 E0.02283
G1 X111.620 Y91.011 E0.57436
G1 X111.175 Y91.011 E0.02283
G1 X119.525 Y99.360 E0.60664
G1 X119.525 Y99.805 E0.02283
G1 X110.731 Y91.011 E0.63892
G1 X110.287 Y91.011 E0.02283
G1 X119.525 Y100.249 E0.67120
G1 X119.525 Y100.693 E0.02283
G1 X109.842 Y91.011 E0.70348
G1 X109.398 Y91.011 E0.02283
G1 X119.525 Y101.137 E0.73576
G1 X119.525 Y101.582 E0.02283
G1 X108.954 Y91.011 E0.76804
G1 X108.510 Y91.011 E0.02283
G1 X119.525 Y102.026 E0.80032
G1 X119.525 Y102.470 E0.02283
G1 X108.065 Y91.011 E0.83260
G1 X107.621 Y91.011 E0.02283
G1 X119.525 Y102.915 E0.86488
G1 X119.525 Y103.359 E0.02283
G1 X107.177 Y91.011 E0.89716
G1 X106.732 Y91.011 E0.02283
G1 X119.525 Y103.803 E0.92944
G1 X119.525 Y104.247 E0.02283
G1 X106.288 Y91.011 E0.96172
G1 X105.844 Y91.011 E0.02283
G1 X119.525 Y104.692 E0.99400
G1 X119.525 Y105.136 E0.02283
G1 X105.400 Y91.011 E1.02628
G1 X104.955 Y91.011 E0.02283
G1 X119.525 Y105.580 E1.05856
G1 X119.525 Y106.025 E0.02283
G1 X104.511 Y91.011 E1.09083
G1 X104.067 Y91.011 E0.02283
G1 X119.525 Y106.469 E1.12311
G1 X119.525 Y106.913 E0.02283
G1 X103.622 Y91.011 E1.15539
G1 X103.178 Y91.011 E0.02283
G1 X119.525 Y107.357 E1.18767
G1 X119.525 Y107.802 E0.02283
G1 X102.734 Y91.011 E1.21995
G1 X102.289 Y91.011 E0.02283
G1 X119.525 Y108.246 E1.25223
G1 X119.525 Y108.690 E0.02283
G1 X101.845 Y91.011 E1.28451
G1 X101.653 Y91.011 E0.00989
G1 X101.653 Y91.262 E0.01293
G1 X119.273 Y108.883 E1.28022
G1 X118.829 Y108.883 E0.02283
G1 X101.653 Y91.707 E1.24794
G1 X101.653 Y92.151 E0.02283
G1 X118.384 Y108.883 E1.21566
G1 X117.940 Y108.883 E0.02283
G1 X101.653 Y92.595 E1.18338
G1 X101.653 Y93.040 E0.02283
G1 X117.496 Y108.883 E1.15110
G1 X117.052 Y108.883 E0.02283
G1 X101.653 Y93.484 E1.11882
G1 X101.653 Y93.928 E0.02283
G1 X116.607 Y108.883 E1.08654
G1 X116.163 Y108.883 E0.02283
G1 X101.653 Y94.372 E1.05426
G1 X101.653 Y94.817 E0.02283
G1 X115.719 Y108.883 E1.02198
G1 X115.274 Y108.883 E0.02283
G1 X101.653 Y95.261 E0.98970
G1 X101.653 Y95.705 E0.02283
G1 X114.830 Y108.883 E0.95742
G1 X114.386 Y108.883 E0.02283
G1 X101.653 Y96.150 E0.92514
G1 X101.653 Y96.594 E0.02283
G1 X113.942 Y108.883 E0.89286
G1 X113.497 Y108.883 E0.02283
G1 X101.653 Y97.038 E0.86058
G1 X101.653 Y97.483 E0.02283
G1 X113.053 Y108.883 E0.82830
G1 X112.609 Y108.883 E0.02283
G1 X101.653 Y97.927 E0.79602
G1 X101.653 Y98.371 E0.02283
G1 X112.164 Y108.883 E0.76374
G1 X111.720 Y108.883 E0.02283
G1 X101.653 Y98.815 E0.73146
G1 X101.653 Y99.260 E0.02283
G1 X111.276 Y108.883 E0.69918
G1 X110.832 Y108.883 E0.02283
G1 X101.653 Y99.704 E0.66690
G1 X101.653 Y100.148 E0.02283
G1 X110.387 Y108.883 E0.63462
G1 X109.943 Y108.883 E0.02283
G1 X101.653 Y100.593 E0.60234
G1 X101.653 Y101.037 E0.02283
G1 X109.499 Y108.883 E0.57006
G1 X109.054 Y108.883 E0.02283
G1 X101.653 Y101.481 E0.53778
G1 X101.653 Y101.925 E0.02283
G1 X108.610 Y108.883 E0.50550
G1 X108.166 Y108.883 E0.02283
G1 X101.653 Y102.370 E0.47322
G1 X101.653 Y102.814 E0.02283
G1 X107.722 Y108.883 E0.44094
G1 X107.277 Y108.883 E0.02283
G1 X101.653 Y103.258 E0.40866
G1 X101.653 Y103.703 E0.02283
G1 X106.833 Y108.883 E0.37638
G1 X106.389 Y108.883 E0.02283
G1 X101.653 Y104.147 E0.34410
G1 X101.653 Y104.591 E0.02283
G1 X105.944 Y108.883 E0.31182
G1 X105.500 Y108.883 E0.02283
G1 X101.653 Y105.035 E0.27954
G1 X101.653 Y105.480 E0.02283
G1 X105.056 Y108.883 E0.24726
G1 X104.612 Y108.883 E0.02283
G1 X101.653 Y105.924 E0.21498
G1 X101.653 Y106.368 E0.02283
G1 X104.167 Y108.883 E0.18270
G1 X103.723 Y108.883 E0.02283
G1 X101.653 Y106.813 E0.15042
G1 X101.653 Y107.257 E0.02283
G1 X103.279 Y108.883 E0.11814
G1 X102.834 Y108.883 E0.02283
G1 X101.653 Y107.701 E0.08586
G1 X101.653 Y108.145 E0.02283
G1 X102.390 Y108.883 E0.05358
G1 X101.946 Y108.883 E0.02283
G1 X101.511 Y108.448 E0.03157
; stop printing object Würfel_20mm.STL id:0 copy 0
; printing object Würfel_20mm.STL id:1 copy 0
; stop printing object Würfel_20mm.STL id:1 copy 0
; printing object Würfel_20mm.STL id:2 copy 0
; stop printing object Würfel_20mm.STL id:2 copy 0
; printing object Würfel_20mm.STL id:3 copy 0
; stop printing object Würfel_20mm.STL id:3 copy 0
G1 E-1.00000 F2400.00000
G1 Z1.700000 F21000.000
; custom gcode: end_filament_gcode
; Filament-specific end gcode
;END gcode for filament
; custom gcode end: end_filament_gcode
T1
; custom gcode: start_filament_gcode
; Filament gcode
; custom gcode end: start_filament_gcode
; printing object Würfel_20mm.STL id:0 copy 0
; stop printing object Würfel_20mm.STL id:0 copy 0
; printing object Würfel_20mm.STL id:1 copy 0
G1 E-3.50000 F2400.00000
G1 X131.000 Y109.658 F21000.000
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Perimeter
G1 F1800.000
G1 X131.000 Y91.314 E0.95835
G1 X149.343 Y91.314 E0.95835
G1 X149.343 Y109.658 E0.95835
G1 X131.060 Y109.658 E0.95521
G1 X130.685 Y109.972 F21000.000
G1 F1800.000
G1 X130.685 Y91.000 E0.99117
G1 X149.657 Y91.000 E0.99117
G1 X149.657 Y109.972 E0.99117
G1 X130.745 Y109.972 E0.98804
G1 X130.371 Y110.286 F21000.000
;TYPE:External perimeter
G1 F1800.000
G1 X130.371 Y90.686 E1.02400
G1 X149.971 Y90.686 E1.02400
G1 X149.971 Y110.286 E1.02400
G1 X130.431 Y110.286 E1.02087
G1 X130.571 Y109.940 F21000.000
G1 E-3.50000 F2400.00000
G1 Z0.900000 F21000.000
G1 X148.614 Y91.409
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Solid infill
G1 F1800.000
G1 X149.107 Y91.902 E0.03587
G1 X149.107 Y92.347 E0.02283
G1 X148.311 Y91.550 E0.05788
G1 X147.866 Y91.550 E0.02283
G1 X149.107 Y92.791 E0.09016
G1 X149.107 Y93.235 E0.02283
G1 X147.422 Y91.550 E0.12244
G1 X146.978 Y91.550 E0.02283
G1 X149.107 Y93.679 E0.15472
G1 X149.107 Y94.124 E0.02283
G1 X146.534 Y91.550 E0.18700
G1 X146.089 Y91.550 E0.02283
G1 X149.107 Y94.568 E0.21928
G1 X149.107 Y95.012 E0.02283
G1 X145.645 Y91.550 E0.25156
G1 X145.201 Y91.550 E0.02283
G1 X149.107 Y95.457 E0.28384
G1 X149.107 Y95.901 E0.02283
G1 X144.756 Y91.550 E0.31612
G1 X144.312 Y91.550 E0.02283
G1 X149.107 Y96.345 E0.34840
G1 X149.107 Y96.789 E0.02283
G1 X143.868 Y91.550 E0.38068
G1 X143.424 Y91.550 E0.02283
G1 X149.107 Y97.234 E0.41296
G1 X149.107 Y97.678 E0.02283
G1 X142.979 Y91.550 E0.44524
G1 X142.535 Y91.550 E0.02283
G1 X149.107 Y98.122 E0.47752
G1 X149.107 Y98.567 E0.02283
G1 X142.091 Y91.550 E0.50980
G1 X141.646 Y91.550 E0.02283
G1 X149.107 Y99.011 E0.54208
G1 X149.107 Y99.455 E0.02283
G1 X141.202 Y91.550 E0.57436
G1 X140.758 Y91.550 E0.02283
G1 X149.107 Y99.900 E0.60664
G1 X149.107 Y100.344 E0.02283
G1 X140.314 Y91.550 E0.63892
G1 X139.869 Y91.550 E0.02283
G1 X149.107 Y100.788 E0.67120
G1 X149.107 Y101.232 E0.02283
G1 X139.425 Y91.550 E0.70348
G1 X138.981 Y91.550 E0.02283
G1 X149.107 Y101.677 E0.73576
G1 X149.107 Y102.121 E0.02283
G1 X138.536 Y91.550 E0.76804
G1 X138.092 Y91.550 E0.02283
G1 X149.107 Y102.565 E0.80032
G1 X149.107 Y103.010 E0.02283
G1 X137.648 Y91.550 E0.83260
G1 X137.204 Y91.550 E0.02283
G1 X149.107 Y103.454 E0.86488
G1 X149.107 Y103.898 E0.02283
G1 X136.759 Y91.550 E0.89716
G1 X136.315 Y91.550 E0.02283
G1 X149.107 Y104.342 E0.92944
G1 X149.107 Y104.787 E0.02283
G1 X135.871 Y91.550 E0.96172
G1 X135.426 Y91.550 E0.02283
G1 X149.107 Y105.231 E0.99400
G1 X149.107 Y105.675 E0.02283
G1 X134.982 Y91.550 E1.02628
G1 X134.538 Y91.550 E0.02283
G1 X149.107 Y106.120 E1.05856
G1 X149.107 Y106.564 E0.02283
G1 X134.094 Y91.550 E1.09083
G1 X133.649 Y91.550 E0.02283
G1 X149.107 Y107.008 E1.12311
G1 X149.107 Y107.452 E0.02283
G1 X133.205 Y91.550 E1.15539
G1 X132.761 Y91.550 E0.02283
G1 X149.107 Y107.897 E1.18767
G1 X149.107 Y108.341 E0.02283
G1 X132.316 Y91.550 E1.21995
G1 X131.872 Y91.550 E0.02283
G1 X149.107 Y108.785 E1.25223
G1 X149.107 Y109.230 E0.02283
G1 X131.428 Y91.550 E1.28451
G1 X131.235 Y91.550 E0.00989
G1 X131.235 Y91.802 E0.01293
G1 X148.856 Y109.422 E1.28022
G1 X148.411 Y109.422 E0.02283
G1 X131.235 Y92.246 E1.24794
G1 X131.235 Y92.690 E0.02283
G1 X147.967 Y109.422 E1.21566
G1 X147.523 Y109.422 E0.02283
G1 X131.235 Y93.135 E1.18338
G1 X131.235 Y93.579 E0.02283
G1 X147.079 Y109.422 E1.15110
G1 X146.634 Y109.422 E0.02283
G1 X131.235 Y94.023 E1.11882
G1 X131.235 Y94.467 E0.02283
G1 X146.190 Y109.422 E1.08654
G1 X145.746 Y109.422 E0.02283
G1 X131.235 Y94.912 E1.05426
G1 X131.235 Y95.356 E0.02283
G1 X145.301 Y109.422 E1.02198
G1 X144.857 Y109.422 E0.02283
G1 X131.235 Y95.800 E0.98970
G1 X131.235 Y96.245 E0.02283
G1 X144.413 Y109.422 E0.95742
G1 X143.969 Y109.422 E0.02283
G1 X131.235 Y96.689 E0.92514
G1 X131.235 Y97.133 E0.02283
G1 X143.524 Y109.422 E0.89286
G1 X143.080 Y109.422 E0.02283
G1 X131.235 Y97.577 E0.86058
G1 X131.235 Y98.022 E0.02283
G1 X142.636 Y109.422 E0.82830
G1 X142.191 Y109.422 E0.02283
G1 X131.235 Y98.466 E0.79602
G1 X131.235 Y98.910 E0.02283
G1 X141.747 Y109.422 E0.76374
G1 X141.303 Y109.422 E0.02283
G1 X131.235 Y99.355 E0.73146
G1 X131.235 Y99.799 E0.02283
G1 X140.858 Y109.422 E0.69918
G1 X140.414 Y109.422 E0.02283
G1 X131.235 Y100.243 E0.66690
G1 X131.235 Y100.687 E0.02283
G1 X139.970 Y109.422 E0.63462
G1 X139.526 Y109.422 E0.02283
G1 X131.235 Y101.132 E0.60234
G1 X131.235 Y101.576 E0.02283
G1 X139.081 Y109.422 E0.57006
G1 X138.637 Y109.422 E0.02283
G1 X131.235 Y102.020 E0.53778
G1 X131.235 Y102.465 E0.02283
G1 X138.193 Y109.422 E0.50550
G1 X137.748 Y109.422 E0.02283
G1 X131.235 Y102.909 E0.47322
G1 X131.235 Y103.353 E0.02283
G1 X137.304 Y109.422 E0.44094
G1 X136.860 Y109.422 E0.02283
G1 X131.235 Y103.797 E0.40866
G1 X131.235 Y104.242 E0.02283
G1 X136.416 Y109.422 E0.37638
G1 X135.971 Y109.422 E0.02283
G1 X131.235 Y104.686 E0.34410
G1 X131.235 Y105.130 E0.02283
G1 X135.527 Y109.422 E0.31182
G1 X135.083 Y109.422 E0.02283
G1 X131.235 Y105.575 E0.27954
G1 X131.235 Y106.019 E0.02283
G1 X134.638 Y109.422 E0.24726
G1 X134.194 Y109.422 E0.02283
G1 X131.235 Y106.463 E0.21498
G1 X131.235 Y106.907 E0.02283
G1 X133.750 Y109.422 E0.18270
G1 X133.306 Y109.422 E0.02283
G1 X131.235 Y107.352 E0.15042
G1 X131.235 Y107.796 E0.02283
G1 X132.861 Y109.422 E0.11814
G1 X132.417 Y109.422 E0.02283
G1 X131.235 Y108.240 E0.08586
G1 X131.235 Y108.685 E0.02283
G1 X131.973 Y109.422 E0.05358
G1 X131.528 Y109.422 E0.02283
G1 X131.094 Y108.988 E0.03157
; stop printing object Würfel_20mm.STL id:1 copy 0
; printing object Würfel_20mm.STL id:2 copy 0
; stop printing object Würfel_20mm.STL id:2 copy 0
; printing object Würfel_20mm.STL id:3 copy 0
; stop printing object Würfel_20mm.STL id:3 copy 0
G1 E-1.00000 F2400.00000
G1 Z1.700000 F21000.000
; custom gcode: end_filament_gcode
; Filament-specific end gcode
;END gcode for filament
; custom gcode end: end_filament_gcode
T2
; custom gcode: start_filament_gcode
; Filament gcode
; custom gcode end: start_filament_gcode
; printing object Würfel_20mm.STL id:0 copy 0
; stop printing object Würfel_20mm.STL id:0 copy 0
; printing object Würfel_20mm.STL id:1 copy 0
; stop printing object Würfel_20mm.STL id:1 copy 0
; printing object Würfel_20mm.STL id:2 copy 0
G1 E-3.50000 F2400.00000
G1 X161.066 Y108.988 F21000.000
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Perimeter
G1 F1800.000
G1 X161.066 Y90.762 E0.95221
G1 X179.409 Y90.762 E0.95835
G1 X179.409 Y109.105 E0.95835
G1 X161.066 Y109.105 E0.95835
G1 X161.066 Y109.048 E0.00300
G1 X160.752 Y109.419 F21000.000
G1 F1800.000
G1 X160.752 Y90.447 E0.99117
G1 X179.724 Y90.447 E0.99117
G1 X179.724 Y109.419 E0.99117
G1 X160.812 Y109.419 E0.98804
G1 X160.438 Y109.733 F21000.000
;TYPE:External perimeter
G1 F1800.000
G1 X160.438 Y90.133 E1.02400
G1 X180.038 Y90.133 E1.02400
G1 X180.038 Y109.733 E1.02400
G1 X160.498 Y109.733 E1.02087
G1 X160.638 Y109.387 F21000.000
G1 E-3.50000 F2400.00000
G1 Z0.900000 F21000.000
G1 X178.680 Y90.856
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Solid infill
G1 F1800.000
G1 X179.174 Y91.350 E0.03587
G1 X179.174 Y91.794 E0.02283
G1 X178.377 Y90.997 E0.05788
G1 X177.933 Y90.997 E0.02283
G1 X179.174 Y92.238 E0.09016
G1 X179.174 Y92.682 E0.02283
G1 X177.489 Y90.997 E0.12244
G1 X177.044 Y90.997 E0.02283
G1 X179.174 Y93.127 E0.15472
G1 X179.174 Y93.571 E0.02283
G1 X176.600 Y90.997 E0.18700
G1 X176.156 Y90.997 E0.02283
G1 X179.174 Y94.015 E0.21928
G1 X179.174 Y94.460 E0.02283
G1 X175.711 Y90.997 E0.25156
G1 X175.267 Y90.997 E0.02283
G1 X179.174 Y94.904 E0.28384
G1 X179.174 Y95.348 E0.02283
G1 X174.823 Y90.997 E0.31612
G1 X174.379 Y90.997 E0.02283
G1 X179.174 Y95.792 E0.34840
G1 X179.174 Y96.237 E0.02283
G1 X173.934 Y90.997 E0.38068
G1 X173.490 Y90.997 E0.02283
G1 X179.174 Y96.681 E0.41296
G1 X179.174 Y97.125 E0.02283
G1 X173.046 Y90.997 E0.44524
G1 X172.601 Y90.997 E0.02283
G1 X179.174 Y97.570 E0.47752
G1 X179.174 Y98.014 E0.02283
G1 X172.157 Y90.997 E0.50980
G1 X171.713 Y90.997 E0.02283
G1 X179.174 Y98.458 E0.54208
G1 X179.174 Y98.902 E0.02283
G1 X171.269 Y90.997 E0.57436
G1 X170.824 Y90.997 E0.02283
G1 X179.174 Y99.347 E0.60664
G1 X179.174 Y99.791 E0.02283
G1 X170.380 Y90.997 E0.63892
G1 X169.936 Y90.997 E0.02283
G1 X179.174 Y100.235 E0.67120
G1 X179.174 Y100.680 E0.02283
G1 X169.491 Y90.997 E0.70348
G1 X169.047 Y90.997 E0.02283
G1 X179.174 Y101.124 E0.73576
G1 X179.174 Y101.568 E0.02283
G1 X168.603 Y90.997 E0.76804
G1 X168.159 Y90.997 E0.02283
G1 X179.174 Y102.012 E0.80032
G1 X179.174 Y102.457 E0.02283
G1 X167.714 Y90.997 E0.83260
G1 X167.270 Y90.997 E0.02283
G1 X179.174 Y102.901 E0.86488
G1 X179.174 Y103.345 E0.02283
G1 X166.826 Y90.997 E0.89716
G1 X166.381 Y90.997 E0.02283
G1 X179.174 Y103.790 E0.92944
G1 X179.174 Y104.234 E0.02283
G1 X165.937 Y90.997 E0.96172
G1 X165.493 Y90.997 E0.02283
G1 X179.174 Y104.678 E0.99400
G1 X179.174 Y105.122 E0.02283
G1 X165.049 Y90.997 E1.02628
G1 X164.604 Y90.997 E0.02283
G1 X179.174 Y105.567 E1.05856
G1 X179.174 Y106.011 E0.02283
G1 X164.160 Y90.997 E1.09083
G1 X163.716 Y90.997 E0.02283
G1 X179.174 Y106.455 E1.12311
G1 X179.174 Y106.900 E0.02283
G1 X163.271 Y90.997 E1.15539
G1 X162.827 Y90.997 E0.02283
G1 X179.174 Y107.344 E1.18767
G1 X179.174 Y107.788 E0.02283
G1 X162.383 Y90.997 E1.21995
G1 X161.939 Y90.997 E0.02283
G1 X179.174 Y108.232 E1.25223
G1 X179.174 Y108.677 E0.02283
G1 X161.494 Y90.997 E1.28451
G1 X161.302 Y90.997 E0.00989
G1 X161.302 Y91.249 E0.01293
G1 X178.922 Y108.869 E1.28022
G1 X178.478 Y108.869 E0.02283
G1 X161.302 Y91.693 E1.24794
G1 X161.302 Y92.137 E0.02283
G1 X178.034 Y108.869 E1.21566
G1 X177.589 Y108.869 E0.02283
G1 X161.302 Y92.582 E1.18338
G1 X161.302 Y93.026 E0.02283
G1 X177.145 Y108.869 E1.15110
G1 X176.701 Y108.869 E0.02283
G1 X161.302 Y93.470 E1.11882
G1 X161.302 Y93.915 E0.02283
G1 X176.256 Y108.869 E1.08654
G1 X175.812 Y108.869 E0.02283
G1 X161.302 Y94.359 E1.05426
G1 X161.302 Y94.803 E0.02283
G1 X175.368 Y108.869 E1.02198
G1 X174.924 Y108.869 E0.02283
G1 X161.302 Y95.247 E0.98970
G1 X161.302 Y95.692 E0.02283
G1 X174.479 Y108.869 E0.95742
G1 X174.035 Y108.869 E0.02283
G1 X161.302 Y96.136 E0.92514
G1 X161.302 Y96.580 E0.02283
G1 X173.591 Y108.869 E0.89286
G1 X173.146 Y108.869 E0.02283
G1 X161.302 Y97.025 E0.86058
G1 X161.302 Y97.469 E0.02283
G1 X172.702 Y108.869 E0.82830
G1 X172.258 Y108.869 E0.02283
G1 X161.302 Y97.913 E0.79602
G1 X161.302 Y98.358 E0.02283
G1 X171.814 Y108.869 E0.76374
G1 X171.369 Y108.869 E0.02283
G1 X161.302 Y98.802 E0.73146
G1 X161.302 Y99.246 E0.02283
G1 X170.925 Y108.869 E0.69918
G1 X170.481 Y108.869 E0.02283
G1 X161.302 Y99.690 E0.66690
G1 X161.302 Y100.135 E0.02283
G1 X170.036 Y108.869 E0.63462
G1 X169.592 Y108.869 E0.02283
G1 X161.302 Y100.579 E0.60234
G1 X161.302 Y101.023 E0.02283
G1 X169.148 Y108.869 E0.57006
G1 X168.704 Y108.869 E0.02283
G1 X161.302 Y101.468 E0.53778
G1 X161.302 Y101.912 E0.02283
G1 X168.259 Y108.869 E0.50550
G1 X167.815 Y108.869 E0.02283
G1 X161.302 Y102.356 E0.47322
G1 X161.302 Y102.800 E0.02283
G1 X167.371 Y108.869 E0.44094
G1 X166.926 Y108.869 E0.02283
G1 X161.302 Y103.245 E0.40866
G1 X161.302 Y103.689 E0.02283
G1 X166.482 Y108.869 E0.37638
G1 X166.038 Y108.869 E0.02283
G1 X161.302 Y104.133 E0.34410
G1 X161.302 Y104.578 E0.02283
G1 X165.593 Y108.869 E0.31182
G1 X165.149 Y108.869 E0.02283
G1 X161.302 Y105.022 E0.27954
G1 X161.302 Y105.466 E0.02283
G1 X164.705 Y108.869 E0.24726
G1 X164.261 Y108.869 E0.02283
G1 X161.302 Y105.910 E0.21498
G1 X161.302 Y106.355 E0.02283
G1 X163.816 Y108.869 E0.18270
G1 X163.372 Y108.869 E0.02283
G1 X161.302 Y106.799 E0.15042
G1 X161.302 Y107.243 E0.02283
G1 X162.928 Y108.869 E0.11814
G1 X162.483 Y108.869 E0.02283
G1 X161.302 Y107.688 E0.08586
G1 X161.302 Y108.132 E0.02283
G1 X162.039 Y108.869 E0.05358
G1 X161.595 Y108.869 E0.02283
G1 X161.160 Y108.435 E0.03157
; stop printing object Würfel_20mm.STL id:2 copy 0
; printing object Würfel_20mm.STL id:3 copy 0
; stop printing object Würfel_20mm.STL id:3 copy 0
G1 E-1.00000 F2400.00000
G1 Z1.700000 F21000.000
; custom gcode: end_filament_gcode
; Filament-specific end gcode
;END gcode for filament
; custom gcode end: end_filament_gcode
T3
; custom gcode: start_filament_gcode
; Filament gcode
; custom gcode end: start_filament_gcode
; printing object Würfel_20mm.STL id:0 copy 0
; stop printing object Würfel_20mm.STL id:0 copy 0
; printing object Würfel_20mm.STL id:1 copy 0
; stop printing object Würfel_20mm.STL id:1 copy 0
; printing object Würfel_20mm.STL id:2 copy 0
; stop printing object Würfel_20mm.STL id:2 copy 0
; printing object Würfel_20mm.STL id:3 copy 0
G1 E-3.50000 F2400.00000
G1 X190.469 Y109.252 F21000.000
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Perimeter
G1 F1800.000
G1 X190.469 Y90.909 E0.95835
G1 X208.813 Y90.909 E0.95835
G1 X208.813 Y109.252 E0.95835
G1 X190.529 Y109.252 E0.95521
G1 X190.155 Y109.567 F21000.000
G1 F1800.000
G1 X190.155 Y90.595 E0.99117
G1 X209.127 Y90.595 E0.99117
G1 X209.127 Y109.567 E0.99117
G1 X190.215 Y109.567 E0.98804
G1 X189.841 Y109.881 F21000.000
;TYPE:External perimeter
G1 F1800.000
G1 X189.841 Y90.281 E1.02400
G1 X209.441 Y90.281 E1.02400
G1 X209.441 Y109.881 E1.02400
G1 X189.901 Y109.881 E1.02087
G1 X190.041 Y109.534 F21000.000
G1 E-3.50000 F2400.00000
G1 Z0.900000 F21000.000
G1 X208.083 Y91.003
G1 Z0.400000
G1 E3.50000 F2400.00000
;TYPE:Solid infill
G1 F1800.000
G1 X208.577 Y91.497 E0.03587
G1 X208.577 Y91.941 E0.02283
G1 X207.780 Y91.145 E0.05788
G1 X207.336 Y91.145 E0.02283
G1 X208.577 Y92.386 E0.09016
G1 X208.577 Y92.830 E0.02283
G1 X206.892 Y91.145 E0.12244
G1 X206.448 Y91.145 E0.02283
G1 X208.577 Y93.274 E0.15472
G1 X208.577 Y93.718 E0.02283
G1 X206.003 Y91.145 E0.18700
G1 X205.559 Y91.145 E0.02283
G1 X208.577 Y94.163 E0.21928
G1 X208.577 Y94.607 E0.02283
G1 X205.115 Y91.145 E0.25156
G1 X204.670 Y91.145 E0.02283
G1 X208.577 Y95.051 E0.28384
G1 X208.577 Y95.496 E0.02283
G1 X204.226 Y91.145 E0.31612
G1 X203.782 Y91.145 E0.02283
G1 X208.577 Y95.940 E0.34840
G1 X208.577 Y96.384 E0.02283
G1 X203.337 Y91.145 E0.38068
G1 X202.893 Y91.145 E0.02283
G1 X208.577 Y96.828 E0.41296
G1 X208.577 Y97.273 E0.02283
G1 X202.449 Y91.145 E0.44524
G1 X202.005 Y91.145 E0.02283
G1 X208.577 Y97.717 E0.47752
G1 X208.577 Y98.161 E0.02283
G1 X201.560 Y91.145 E0.50980
G1 X201.116 Y91.145 E0.02283
G1 X208.577 Y98.606 E0.54208
G1 X208.577 Y99.050 E0.02283
G1 X200.672 Y91.145 E0.57436
G1 X200.227 Y91.145 E0.02283
G1 X208.577 Y99.494 E0.60664
G1 X208.577 Y99.938 E0.02283
G1 X199.783 Y91.145 E0.63892
G1 X199.339 Y91.145 E0.02283
G1 X208.577 Y100.383 E0.67120
G1 X208.577 Y100.827 E0.02283
G1 X198.895 Y91.145 E0.70348
G1 X198.450 Y91.145 E0.02283
G1 X208.577 Y101.271 E0.73576
G1 X208.577 Y101.716 E0.02283
G1 X198.006 Y91.145 E0.76804
G1 X197.562 Y91.145 E0.02283
G1 X208.577 Y102.160 E0.80032
G1 X208.577 Y102.604 E0.02283
G1 X197.117 Y91.145 E0.83260
G1 X196.673 Y91.145 E0.02283
G1 X208.577 Y103.048 E0.86488
G1 X208.577 Y103.493 E0.02283
G1 X196.229 Y91.145 E0.89716
G1 X195.785 Y91.145 E0.02283
G1 X208.577 Y103.937 E0.92944
G1 X208.577 Y104.381 E0.02283
G1 X195.340 Y91.145 E0.96172
G1 X194.896 Y91.145 E0.02283
G1 X208.577 Y104.826 E0.99400
G1 X208.577 Y105.270 E0.02283
G1 X194.452 Y91.145 E1.02628
G1 X194.007 Y91.145 E0.02283
G1 X208.577 Y105.714 E1.05856
G1 X208.577 Y106.158 E0.02283
G1 X193.563 Y91.145 E1.09083
G1 X193.119 Y91.145 E0.02283
G1 X208.577 Y106.603 E1.12311
G1 X208.577 Y107.047 E0.02283
G1 X192.675 Y91.145 E1.15539
G1 X192.230 Y91.145 E0.02283
G1 X208.577 Y107.491 E1.18767
G1 X208.577 Y107.936 E0.02283
G1 X191.786 Y91.145 E1.21995
G1 X191.342 Y91.145 E0.02283
G1 X208.577 Y108.380 E1.25223
G1 X208.577 Y108.824 E0.02283
G1 X190.897 Y91.145 E1.28451
G1 X190.705 Y91.145 E0.00989
G1 X190.705 Y91.396 E0.01293
G1 X208.325 Y109.017 E1.28022
G1 X207.881 Y109.017 E0.02283
G1 X190.705 Y91.841 E1.24794
G1 X190.705 Y92.285 E0.02283
G1 X207.437 Y109.017 E1.21566
G1 X206.992 Y109.017 E0.02283
G1 X190.705 Y92.729 E1.18338
G1 X190.705 Y93.174 E0.02283
G1 X206.548 Y109.017 E1.15110
G1 X206.104 Y109.017 E0.02283
G1 X190.705 Y93.618 E1.11882
G1 X190.705 Y94.062 E0.02283
G1 X205.660 Y109.017 E1.08654
G1 X205.215 Y109.017 E0.02283
G1 X190.705 Y94.506 E1.05426
G1 X190.705 Y94.951 E0.02283
G1 X204.771 Y109.017 E1.02198
G1 X204.327 Y109.017 E0.02283
G1 X190.705 Y95.395 E0.98970
G1 X190.705 Y95.839 E0.02283
G1 X203.882 Y109.017 E0.95742
G1 X203.438 Y109.017 E0.02283
G1 X190.705 Y96.284 E0.92514
G1 X190.705 Y96.728 E0.02283
G1 X202.994 Y109.017 E0.89286
G1 X202.550 Y109.017 E0.02283
G1 X190.705 Y97.172 E0.86058
G1 X190.705 Y97.616 E0.02283
G1 X202.105 Y109.017 E0.82830
G1 X201.661 Y109.017 E0.02283
G1 X190.705 Y98.061 E0.79602
G1 X190.705 Y98.505 E0.02283
G1 X201.217 Y109.017 E0.76374
G1 X200.772 Y109.017 E0.02283
G1 X190.705 Y98.949 E0.73146
G1 X190.705 Y99.394 E0.02283
G1 X200.328 Y109.017 E0.69918
G1 X199.884 Y109.017 E0.02283
G1 X190.705 Y99.838 E0.66690
G1 X190.705 Y100.282 E0.02283
G1 X199.440 Y109.017 E0.63462
G1 X198.995 Y109.017 E0.02283
G1 X190.705 Y100.726 E0.60234
G1 X190.705 Y101.171 E0.02283
G1 X198.551 Y109.017 E0.57006
G1 X198.107 Y109.017 E0.02283
G1 X190.705 Y101.615 E0.53778
G1 X190.705 Y102.059 E0.02283
G1 X197.662 Y109.017 E0.50550
G1 X197.218 Y109.017 E0.02283
G1 X190.705 Y102.504 E0.47322
G1 X190.705 Y102.948 E0.02283
G1 X196.774 Y109.017 E0.44094
G1 X196.330 Y109.017 E0.02283
G1 X190.705 Y103.392 E0.40866
G1 X190.705 Y103.836 E0.02283
G1 X195.885 Y109.017 E0.37638
G1 X195.441 Y109.017 E0.02283
G1 X190.705 Y104.281 E0.34410
G1 X190.705 Y104.725 E0.02283
G1 X194.997 Y109.017 E0.31182
G1 X194.552 Y109.017 E0.02283
G1 X190.705 Y105.169 E0.27954
G1 X190.705 Y105.614 E0.02283
G1 X194.108 Y109.017 E0.24726
G1 X193.664 Y109.017 E0.02283
G1 X190.705 Y106.058 E0.21498
G1 X190.705 Y106.502 E0.02283
G1 X193.220 Y109.017 E0.18270
G1 X192.775 Y109.017 E0.02283
G1 X190.705 Y106.946 E0.15042
G1 X190.705 Y107.391 E0.02283
G1 X192.331 Y109.017 E0.11814
G1 X191.887 Y109.017 E0.02283
G1 X190.705 Y107.835 E0.08586
G1 X190.705 Y108.279 E0.02283
G1 X191.442 Y109.017 E0.05358
G1 X190.998 Y109.017 E0.02283
G1 X190.563 Y108.582 E0.03157
; stop printing object Würfel_20mm.STL id:3 copy 0
G1 E-3.50000 F2400.00000
G1 Z0.900000 F21000.000
;TYPE:Custom
; custom gcode: end_filament_gcode
; Filament-specific end gcode
;END gcode for filament
; custom gcode end: end_filament_gcode
; custom gcode: end_filament_gcode
; Filament-specific end gcode
;END gcode for filament
; custom gcode end: end_filament_gcode
; custom gcode: end_filament_gcode
; Filament-specific end gcode
;END gcode for filament
; custom gcode end: end_filament_gcode
; custom gcode: end_filament_gcode
; Filament-specific end gcode
;END gcode for filament
; custom gcode end: end_filament_gcode
; custom gcode: end_gcode
; Drop off the tool
T-1

; Disable Mesh Compensation.
G29 S2

; Park
G91
G1 Z2 F1000
G90
G1 X0 Y0 F50000

M0	;turn off all heaters
; custom gcode end: end_gcode
; filament used [mm] = 65.94, 65.94, 65.94, 65.94
; filament used [cm3] = 0.16, 0.16, 0.16, 0.16
; filament used [g] = 0.21, 0.21, 0.21, 0.21
; filament cost = 0.01, 0.01, 0.01, 0.01

; total filament used [g] = 0.82
; total filament cost = 0.03
; estimated printing time (normal mode) = 3m 3s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; bed_custom_model =
; bed_custom_texture =
; bed_shape = 0x0,300x0,300x200,0x200
; bed_temperature = 60,60,60,60
; before_layer_gcode =
; between_objects_gcode =
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100,100,100,100
; bridge_flow_ratio = 100%
; bridge_overlap = 100%
; bridge_speed = 60
; bridge_speed_internal = 60
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0,0,0,0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1,1,1,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = ""
; default_print_profile =
; deretract_speed = 0,0,0,0
; disable_fan_first_layers = 3,3,3,3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = ; Drop off the tool\nT-1\n\n; Disable Mesh Compensation.\nG29 S2\n\n; Park\nG91\nG1 Z2 F1000\nG90\nG1 X0 Y0 F50000\n\nM0	;turn off all heaters
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_width = 100%
; external_perimeter_fan_speed = -1,-1,-1,-1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 60
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ;;;
; extruder_fan_offset = 0%,0%,0%,0%
; extruder_offset = 0x0,0x0,0x0,0x0
; extruder_temperature_offset = 0,0,0,0
; extrusion_axis = E
; extrusion_multiplier = 1,1,1,1
; extrusion_width = 100%
; fan_always_on = 0,0,0,0
; fan_below_layer_time = 60,60,60,60
; fan_kickstart = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = -0.5
; feature_gcode =
; filament_colour = #0000FF;#FB0207;#FECC66;#FFFFFF
; filament_cooling_final_speed = 3.4,3.4,3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2,2.2,2.2
; filament_cooling_moves = 4,4,4,4
; filament_cooling_zone_pause = 0,0,0,0
; filament_cost = 37.33,37.33,37.33,37.33
; filament_density = 1.3,1.3,1.3,1.3
; filament_diameter = 1.75,1.75,1.75,1.75
; filament_dip_extraction_speed = 70,70,70,70
; filament_dip_insertion_speed = 33,33,33,33
; filament_enable_toolchange_part_fan = 0,0,0,0
; filament_enable_toolchange_temp = 1,1,1,1
; filament_load_time = 0,0,0,0
; filament_loading_speed = 28,28,28,28
; filament_loading_speed_start = 3,3,3,3
; filament_max_speed = 0,0,0,0
; filament_max_volumetric_speed = 0,0,0,0
; filament_max_wipe_tower_speed = 0,0,0,0
; filament_melt_zone_pause = 0,0,0,0
; filament_minimal_purge_on_wipe_tower = 0,0,0,0
; filament_notes = ;;;
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PLA - blue";"PLA - red";"PLA - skin";"PLA - white"
; filament_shrink = 100%,100%,100%,100%
; filament_skinnydip_distance = 31,31,31,31
; filament_soluble = 0,0,0,0
; filament_toolchange_delay = 0,0,0,0
; filament_toolchange_part_fan_speed = 50,50,50,50
; filament_toolchange_temp = 175,175,175,175
; filament_type = PLA;PLA;PLA;PLA
; filament_unload_time = 0,0,0,0
; filament_unloading_speed = 90,90,90,90
; filament_unloading_speed_start = 100,100,100,100
; filament_use_fast_skinnydip = 0,0,0,0
; filament_use_skinnydip = 0,0,0,0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5,0.5,0.5,0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 0%
; fill_pattern = gyroid
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_bed_temperature = 60,60,60,60
; first_layer_extrusion_width = 100%
; first_layer_flow_ratio = 100%
; first_layer_height = 100%
; first_layer_infill_speed = 50%
; first_layer_size_compensation = 0
; first_layer_speed = 50%
; first_layer_temperature = 225,225,225,225
; gap_fill = 1
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = 1
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_connection = connected
; infill_dense = 0
; infill_dense_algo = autosmall
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 100%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode =
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100,100,100
; max_layer_height = 0,0,0,0
; max_print_height = 280
; max_print_speed = 80
; max_speed_reduction = 90%,90%,90%,90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode =
; milling_toolchange_start_gcode =
; min_fan_speed = 35,35,35,35
; min_layer_height = 0.05,0.05,0.05,0.05
; min_length = 0.035
; min_print_speed = 10,10,10,10
; min_skirt_length = 0
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes =
; nozzle_diameter = 0.4,0.4,0.4,0.4
; only_one_perimeter_top = 0
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 20
; overhangs_width = 75%
; overhangs_width_speed = 50%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_width = 100%
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_speed = 60
; perimeters = 3
; post_process =
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = E3D Toolchanger
; print_temperature = 0
; printer_model =
; printer_notes =
; printer_settings_id = E3D Toolchanger
; printer_technology = FFF
; printer_variant =
; printer_vendor =
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2,2,2
; retract_before_wipe = 0%,0%,0%,0%
; retract_layer_change = 0,0,0,0
; retract_length = 3.5,3.5,3.5,3.5
; retract_length_toolchange = 1,1,1,1
; retract_lift = 0.5,0.5,0.5,0.5
; retract_lift_above = 0,0,0,0
; retract_lift_below = 0,0,0,0
; retract_lift_first_layer = 1,1,1,1
; retract_lift_top = "All surfaces";"All surfaces";"All surfaces";"All surfaces"
; retract_restart_extra = 0,0,0,0
; retract_restart_extra_toolchange = 2,3,4,5
; retract_speed = 40,40,40,40
; seam_angle_cost = 100%
; seam_position = hidden
; seam_travel_cost = 100%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 6
; skirt_extrusion_width = 100%
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5,5,5,5
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6%
; small_perimeter_speed = 15
; solid_fill_pattern = rectilineargapfill
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 100%
; solid_infill_speed = 60
; spiral_vase = 0
; standby_temperature_delta = 75
; start_filament_gcode = "; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n"
; start_gcode = ; set tool temps\nG10 P0 S[temperature_0] R150;\nG10 P1 S[temperature_1] R150;\nG10 P2 S[temperature_2] R150;\nG10 P3 S[temperature_3] R150;\n\n; set bed temps\nM140 S[bed_temperature] ;set bed temp fast\nM190 S[bed_temperature] ; set bed temp + wait for it\n\n; prepare for print\nG28; home all axes\nG29 S1; enable MeshBedLeveling\nG1 Z5 F5000 ; lift nozzle\n\n; make sure, a tool is selected before print\n{ if current_extruder == 0 }\nT0 ; Select inital tool\n{ endif }\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.2
; support_material_contact_distance_top = 0.2
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 95
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_solid_first_layer = 0
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 225,225,225,225
; template_custom_gcode =
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 1
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 16
; thumbnails = 0x0,0x0
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_with_bed = 1
; time_estimation_compensation = 100%
; toolchange_gcode =
; top_fan_speed = -1,-1,-1,-1
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 100%
; top_solid_infill_speed = 60
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_speed = 350
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0,0,0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0,0,0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 90
; wipe_tower_width = 20
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70
; wiping_volumes_matrix = 0,140,140,140,140,0,140,140,140,140,0,140,140,140,140,0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.01
